{% set name = "seamm-util" %}
{% set version = "2025.12.9" %}
{% set sha256 = "5e4fc6c6245b8910087b43d87684fc1b0a24a92a9202dd97ca32c9dad0c72fe4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-util/seamm_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pint
    - plotly
    - python >={{ python_min }}
    - requests
    - statsmodels

test:
  imports:
    - seamm_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_util
  summary: Utility classes and functions for the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_util/

extra:
  recipe-maintainers:
    - paulsaxe
